name: Push to TestPyPI
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to TestPyPI
        uses: JRubics/poetry-publish@v1.10
        with:
          python_version: "3.8.5"
          poetry_version: "==1.1.11"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "wheel"
