name: Push to PyPI
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-then-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish to PyPI
        uses: ./.github/actions/poetry-pypi
        with:
          repository: "pypi"
          token: ${{ secrets.PYPI_TOKEN }}
