name: Push to TestPyPI
on:
  push:
    branches:
      - 'feature/**'
jobs:
  build-then-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish to TestPyPI
        uses: ./.github/actions/poetry-pypi
        with:
          repository: "testpypi"
          token: ${{ secrets.TESTPYPI_TOKEN }}
