name: Push to TestPyPI
on:
  push:
    branches:
      - develop
jobs:
  build-then-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set package version
        run: |
          VERSION="$(grep -Po '^version\s*\=\s*\"\K\d+\.\d+\.\d+' ./pyproject.toml)-$(git rev-parse --short HEAD)"
          sed -E -i 's/^(__version__\s*\=\s*\")[^"]*/\1'"$VERSION"'/g' ./palabros/__init__.py
          sed -E -i 's/^(version\s*\=\s*\")[^"]*/\1'"$VERSION"'/g' ./pyproject.toml
      - name: Build and publish to TestPyPI
        uses: JRubics/poetry-publish@v1.10
        with:
          python_version: "3.8.5"
          poetry_version: "==1.1.11"
          pypi_token: ${{ secrets.TESTPYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"
          build_format: "wheel"
