name: Push to PyPI
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build-then-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.10
        with:
          python_version: "3.8.5"
          poetry_version: "==1.1.11"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          build_format: "wheel"
