name: Test app code
on:
  # pull_request:
  #   branches:
  #     - develop
  #     - master
  push:
    branches:
      - 'feature/**'
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test application using Poetry
        uses: ./.github/actions/poetry-tests
        with:
          lint: true
          test: true
          coverage: true
